apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: 'cert-manager'
    targetRevision: 'v1.13.0'  # Replace with the appropriate version
    # targetRevision: 'v1.16.ยง'  # Replace with the appropriate version    
    helm:
      values: |
        installCRDs: true
        extraArgs:
          - --enable-certificate-owner-ref=true
        webhook:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncWave: 0  # Deploy cert-manager first
