apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: 'cert-manager'
    targetRevision: 'v1.16.0'  
    helm:
      values: |
        global:
          logLevel: 6
        crds:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    
  healthChecks:
    - kind: Deployment
      name: cert-manager
      healthy: true        
