# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: vault-issuer
#   namespace: cert-manager
#   annotations:
#     argocd.argoproj.io/sync-wave: "5"  
# spec:
#   vault:
#     path: pki/sign/istio-role
#     server: "http://vault.vault.svc.cluster.local:8200"  # Vault server URL in the east cluster
#     auth:
#       kubernetes:
#         role: cert-manager-role
#         serviceAccountRef:
#           name: istio-issuer
#           namespace: cert-manager

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager
  namespace: istio-system
spec:
  vault:
    server: http://vault.vault.svc.cluster.local:8200
    path: pki/sign/istio-role
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager-role
        secretRef:
          name: istio-issuer
          key: token