apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-csr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: 'istio-csr'
    targetRevision: 'v0.12.0'  # Replace with the appropriate version
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncWave: 1  # Deploy Istio CSR after cert-manager
