apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-csr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/depends-on: "cert-manager" 
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: 'cert-manager-istio-csr'
    targetRevision: 'v0.12.0'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
